# Generated by Django 4.2.16 on 2026-03-16 16:09

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_transaccion', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Número de Transacción')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto')),
                ('tipo_pago', models.CharField(choices=[('alquiler', 'Pago de Alquiler'), ('deposito', 'Depósito de Garantía'), ('adicional', 'Cargo Adicional'), ('reembolso', 'Reembolso')], default='alquiler', max_length=20, verbose_name='Tipo de Pago')),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta_credito', 'Tarjeta de Crédito'), ('tarjeta_debito', 'Tarjeta de Débito'), ('transferencia', 'Transferencia Bancaria'), ('paypal', 'PayPal'), ('stripe', 'Stripe')], max_length=20, verbose_name='Método de Pago')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('fallido', 'Fallido'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Pago')),
                ('fecha_procesado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Procesado')),
                ('referencia_externa', models.CharField(blank=True, help_text='ID de transacción del procesador de pagos', max_length=200, verbose_name='Referencia Externa')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
