# Generated by Django 4.2.16 on 2026-03-16 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pagos', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['reserva', 'estado'], name='pagos_pago_reserva_cf5cae_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['usuario', 'fecha_pago'], name='pagos_pago_usuario_cd5d58_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['numero_transaccion'], name='pagos_pago_numero__21dd73_idx'),
        ),
    ]
