# Generated by Django 4.2.16 on 2026-03-16 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('reserva_creada', 'Nueva Reserva Creada'), ('reserva_confirmada', 'Reserva Confirmada'), ('reserva_cancelada', 'Reserva Cancelada'), ('reserva_en_curso', 'Alquiler Iniciado'), ('reserva_completada', 'Alquiler Completado'), ('pago_recibido', 'Pago Recibido'), ('recordatorio_entrega', 'Recordatorio de Entrega'), ('recordatorio_devolucion', 'Recordatorio de Devolución'), ('nueva_calificacion', 'Nueva Calificación'), ('admin_nueva_reserva', 'Nueva Reserva (Admin)'), ('admin_nuevo_usuario', 'Nuevo Usuario Registrado')], max_length=30, verbose_name='Tipo')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('url', models.CharField(blank=True, max_length=500, verbose_name='URL')),
                ('leida', models.BooleanField(default=False, verbose_name='Leída')),
                ('leida_at', models.DateTimeField(blank=True, null=True, verbose_name='Leída el')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['usuario', 'leida'], name='core_notifi_usuario_c30a38_idx'), models.Index(fields=['usuario', 'created_at'], name='core_notifi_usuario_846c04_idx')],
            },
        ),
    ]
