# Generated by Django 4.2.16 on 2026-03-16 16:09

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueoDisponibilidad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('tipo_motivo', models.CharField(choices=[('mantenimiento', 'Mantenimiento Programado'), ('reparacion', 'Reparación'), ('reservado_admin', 'Reservado por Administración'), ('inspeccion', 'Inspección Técnica'), ('otro', 'Otro')], default='mantenimiento', max_length=20, verbose_name='Motivo')),
                ('motivo', models.CharField(max_length=300, verbose_name='Descripción del Motivo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bloqueo de Disponibilidad',
                'verbose_name_plural': 'Bloqueos de Disponibilidad',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='CalificacionEquipo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('puntuacion', models.PositiveSmallIntegerField(choices=[(1, '1 estrellas'), (2, '2 estrellas'), (3, '3 estrellas'), (4, '4 estrellas'), (5, '5 estrellas')], verbose_name='Puntuación (1-5)')),
                ('comentario', models.TextField(blank=True, verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='categorias/', verbose_name='Imagen')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('codigo_interno', models.CharField(help_text='Código único del equipo', max_length=50, unique=True, verbose_name='Código Interno')),
                ('marca', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Número de Serie')),
                ('precio_por_dia', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio por Día')),
                ('precio_por_semana', models.DecimalField(blank=True, decimal_places=2, help_text='Precio especial por semana (7 días)', max_digits=10, null=True, verbose_name='Precio por Semana')),
                ('precio_por_mes', models.DecimalField(blank=True, decimal_places=2, help_text='Precio especial por mes (30 días)', max_digits=10, null=True, verbose_name='Precio por Mes')),
                ('deposito_garantia', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Depósito requerido para alquilar el equipo', max_digits=10, verbose_name='Depósito de Garantía')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('rentado', 'Rentado'), ('mantenimiento', 'En Mantenimiento'), ('fuera_servicio', 'Fuera de Servicio')], default='disponible', max_length=20, verbose_name='Estado')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('especificaciones', models.JSONField(blank=True, default=dict, help_text='Especificaciones técnicas del equipo', verbose_name='Especificaciones Técnicas')),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to='equipos/%Y/%m/', verbose_name='Imagen Principal')),
                ('ultima_fecha_mantenimiento', models.DateField(blank=True, null=True, verbose_name='Última Fecha de Mantenimiento')),
                ('proxima_fecha_mantenimiento', models.DateField(blank=True, null=True, verbose_name='Próxima Fecha de Mantenimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipos', to='equipos.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ImagenEquipo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='equipos/%Y/%m/', verbose_name='Imagen')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='equipos.equipo', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Imagen de Equipo',
                'verbose_name_plural': 'Imágenes de Equipos',
                'ordering': ['orden', 'created_at'],
            },
        ),
    ]
