# Generated by Django 4.2.16 on 2026-03-16 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipos', '0001_initial'),
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacionequipo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='calificacionequipo',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='equipos.equipo', verbose_name='Equipo'),
        ),
        migrations.AddField(
            model_name='calificacionequipo',
            name='reserva',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calificacion', to='reservas.reserva', verbose_name='Reserva'),
        ),
        migrations.AddField(
            model_name='bloqueodisponibilidad',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bloqueos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='bloqueodisponibilidad',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to='equipos.equipo', verbose_name='Equipo'),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['categoria', 'disponible'], name='equipos_equ_categor_b486fb_idx'),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['codigo_interno'], name='equipos_equ_codigo__9a7034_idx'),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['estado'], name='equipos_equ_estado_333e5d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='calificacionequipo',
            unique_together={('equipo', 'cliente', 'reserva')},
        ),
    ]
