# Generated by Django 4.2.16 on 2026-03-16 16:09

from decimal import Decimal
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_reserva', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Número de Reserva')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('fecha_entrega_real', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Entrega Real')),
                ('fecha_devolucion_real', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Devolución Real')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Confirmación'), ('confirmada', 'Confirmada'), ('en_curso', 'En Curso'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('vencida', 'Vencida')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('costo_alquiler', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Costo de Alquiler')),
                ('deposito_pagado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Depósito Pagado')),
                ('costo_adicional', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cargos por daños, retrasos, etc.', max_digits=10, verbose_name='Costo Adicional')),
                ('notas_cliente', models.TextField(blank=True, verbose_name='Notas del Cliente')),
                ('notas_admin', models.TextField(blank=True, verbose_name='Notas del Administrador')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmada_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmada el')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-created_at'],
            },
        ),
    ]
