# Generated by Django 4.2.16 on 2026-03-16 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(limit_choices_to={'tipo_usuario': 'cliente'}, on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='equipos.equipo', verbose_name='Equipo'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['cliente', 'estado'], name='reservas_re_cliente_5b00f2_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['equipo', 'fecha_inicio', 'fecha_fin'], name='reservas_re_equipo__81629c_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['numero_reserva'], name='reservas_re_numero__186cfa_idx'),
        ),
    ]
